# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               '$ sudo hoon'
tagline:             'System Software Engineer'
description:         'Robot Navigation, Embedded linux...'
url:                 https://sudo-hoon.github.io
baseurl:             'https://sudo-hoon.github.io'
paginate:            5
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# About/contact
author:
  name:              KIM DO HOON
  url:               https://sudo-hoon.github.io
  email:             dohoon19.kim@gmail.com

# Custom vars
version:             1.0.0

plugins: [jekyll-paginate]

# Tag setting
#collections:
#  tags:
#    output: true
#    permalink: /tags/:path/

#defaults:
#  - scope:
#      path: ''
#      type: tags
#    values:
#      layout: tag

#google_analytics:
#  ua: 'UA-109898110-1'

github:
  repo: 'https://github.com/sudo-hoon/sudo-hoon.github.io'

category_dir: category/
tag_dir: tag/

excerpt_separator: ""
